const KEY='pat-v2';
const legacy=JSON.parse(localStorage.getItem('pat-v1')||'{"tasks":[],"brain":[]}');
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{tasks:legacy.tasks||[],brain:legacy.brain||[],events:[],triage:[],research:[],whatsapp:[],lastSync:null,lastReminderSync:null,lastMailSync:null};
state.whatsapp=state.whatsapp||[];state.triage=state.triage||[];
const $=id=>document.getElementById(id), q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
const todayISO=()=>new Date().toLocaleDateString('en-CA');
const esc=s=>(s||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const save=()=>{localStorage.setItem(KEY,JSON.stringify(state));render();};
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function fmtDate(d){if(!d)return'';return new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short'}).format(new Date(d+'T12:00:00'))}
function fmtTime(v){if(!v)return'';const d=new Date(v);return isNaN(d)?v:new Intl.DateTimeFormat('en-GB',{hour:'2-digit',minute:'2-digit'}).format(d)}
$('todayDate').textContent=new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'long'}).format(new Date());
$('greeting').textContent=(new Date().getHours()<12?'Good morning':new Date().getHours()<18?'Good afternoon':'Good evening')+'.';
$('dueDate').value=todayISO();
function addTask(text,due='',priority=2,extra={}){text=text.trim();if(!text)return;state.tasks.unshift({id:crypto.randomUUID(),text,due,priority:Number(priority),done:false,created:Date.now(),...extra});save()}
window.toggleTask=id=>{const t=state.tasks.find(x=>x.id===id);if(t){t.done=!t.done;save()}};
window.deleteTask=id=>{state.tasks=state.tasks.filter(x=>x.id!==id);save()};
window.deleteResearch=id=>{state.research=state.research.filter(x=>x.id!==id);save()};
window.dismissWhatsApp=id=>{state.whatsapp=state.whatsapp.filter(x=>x.id!==id);save()};
window.dismissTriage=id=>{state.triage=state.triage.filter(x=>x.id!==id);save();toast('Dismissed')};
window.triageToTask=id=>{const t=state.triage.find(x=>x.id===id);if(!t)return;addTask(t.title,todayISO(),t.score>=5?1:2,{source:t.source||'Triage',note:t.note||''});state.triage=state.triage.filter(x=>x.id!==id);save();toast('Added to tasks')};
window.triageToResearch=id=>{const t=state.triage.find(x=>x.id===id);if(!t)return;state.research.unshift({id:crypto.randomUUID(),text:`${t.title}${t.note?` — ${t.note}`:''}`,created:Date.now(),source:t.source||'Triage'});state.triage=state.triage.filter(x=>x.id!==id);save();toast('Moved to research')};
function taskHtml(t){const overdue=t.due&&t.due<todayISO()&&!t.done;const meta=[t.source?t.source:'',t.due?`${overdue?'Overdue · ':''}${fmtDate(t.due)}`:'',t.priority===1?'High priority':''].filter(Boolean).join(' · ');return `<div class="item ${t.done?'done':''}"><input class="check" type="checkbox" ${t.done?'checked':''} onchange="toggleTask('${t.id}')"><div><div class="title">${esc(t.text)}</div>${meta?`<div class="meta">${esc(meta)}</div>`:''}</div><button class="iconBtn" onclick="deleteTask('${t.id}')">×</button></div>`}
function eventHtml(e){const when=e.allDay?'All day':fmtTime(e.start);return `<div class="item"><span class="dot event"></span><div><div class="title">${esc(e.title)}</div><div class="meta">${esc(when)}${e.calendar?` · ${esc(e.calendar)}`:''}</div></div></div>`}
function triageHtml(t){return `<div class="researchCard"><div class="item" style="padding:0;border:0"><span class="dot inbox"></span><div><div class="title">${esc(t.title)}</div><div class="meta">${esc(t.source||'PAT')}${t.sender?` · ${esc(t.sender)}`:''}${t.score?` · score ${t.score}`:''}</div>${t.note?`<div class="meta">${esc(t.note)}</div>`:''}</div><button class="iconBtn" onclick="dismissTriage('${t.id}')">×</button></div><div class="actions"><button class="secondary" onclick="triageToTask('${t.id}')">Make task</button><button class="ghost" onclick="triageToResearch('${t.id}')">Research</button></div></div>`}
function whatsappHtml(w){return `<div class="item"><span class="dot whatsapp"></span><div><div class="title">${esc(w.name)}</div><div class="meta">Unread WhatsApp message</div></div><button class="iconBtn" onclick="dismissWhatsApp('${w.id}')">✓</button></div>`}
function researchHtml(r){return `<div class="researchCard"><div class="item" style="padding:0;border:0"><span class="dot research"></span><div><div class="title">${esc(r.text)}</div><div class="meta">Queued ${new Date(r.created).toLocaleDateString('en-GB')}</div></div><button class="iconBtn" onclick="deleteResearch('${r.id}')">×</button></div><div class="actions"><button class="primary" onclick="researchWithGPT('${r.id}')">Research with ChatGPT</button></div></div>`}
window.researchWithGPT=async id=>{const r=state.research.find(x=>x.id===id);if(!r)return;const p=`Act as my personal assistant. Research this task for me now: ${r.text}. Use current web information where relevant. Give me a concise shortlist, prices/links where applicable, and a clear recommendation. Do the research rather than giving me instructions.`;await navigator.clipboard.writeText(p);toast('Prompt copied — opening ChatGPT');setTimeout(()=>location.href='https://chatgpt.com/',350)};
const HIGH=['action required','urgent','payment','payment failed','overdue','renew','renewal','expires','expiry','appointment','booking','confirm','confirmation needed','delivery problem','failed delivery','account','security','password','verify','verification','reply required','respond','request','deadline','due','school','nursery','invoice','bill','refund','cancellation','cancelled','claim','insurance','mot','tax'];
const MED=['please','reminder','update','change','important','order','delivery','collection','reservation','registration','form','statement','subscription','plan','quote','estimate','review'];
const LOW=['newsletter','sale','offer','discount','promo','promotion','marketing','weekly digest','recommendations','new arrivals'];
function scoreMail(m){const text=`${m.subject||''} ${m.preview||''} ${m.sender||''}`.toLowerCase();let score=m.unread===false?0:1;HIGH.forEach(k=>{if(text.includes(k))score+=3});MED.forEach(k=>{if(text.includes(k))score+=1});LOW.forEach(k=>{if(text.includes(k))score-=2});if(m.flagged)score+=2;return score}
function render(){const open=state.tasks.filter(t=>!t.done),due=open.filter(t=>t.due&&t.due<=todayISO()),events=state.events.filter(e=>(e.date||String(e.start||'').slice(0,10))===todayISO()),triageCount=state.triage.length+state.whatsapp.length;$('mTasks').textContent=open.length;$('mToday').textContent=due.length;$('mEvents').textContent=events.length;$('mTriage').textContent=triageCount;$('briefLine').textContent=due.length||events.length||triageCount?'Here’s what deserves your attention.':'Nothing urgent is shouting at you. Suspiciously civilised.';const priority=[...open].filter(t=>t.priority===1||!t.due||t.due<=todayISO()).sort((a,b)=>a.priority-b.priority||String(a.due).localeCompare(String(b.due))).slice(0,6);$('todayTasks').innerHTML=priority.length?priority.map(taskHtml).join(''):'<div class="empty">No urgent tasks.</div>';$('todayEvents').innerHTML=events.length?events.sort((a,b)=>String(a.start).localeCompare(String(b.start))).map(eventHtml).join(''):'<div class="empty">No calendar events imported for today.</div>';const sortedTriage=[...state.triage].sort((a,b)=>(b.score||0)-(a.score||0));$('triageItems').innerHTML=(state.whatsapp.length?state.whatsapp.map(whatsappHtml).join(''):'')+(sortedTriage.length?sortedTriage.slice(0,8).map(triageHtml).join(''):'')||'<div class="empty">Nothing waiting for triage.</div>';const f=q('.filter.active')?.dataset.filter||'open';let tasks=[...state.tasks];if(f==='open')tasks=tasks.filter(t=>!t.done);if(f==='today')tasks=tasks.filter(t=>!t.done&&(!t.due||t.due<=todayISO()));tasks.sort((a,b)=>Number(a.done)-Number(b.done)||a.priority-b.priority||String(a.due).localeCompare(String(b.due)));$('allTasks').innerHTML=tasks.length?tasks.map(taskHtml).join(''):'<div class="empty">No tasks in this view.</div>';$('brainItems').innerHTML=state.brain.slice(0,8).map(n=>`<div class="item"><span class="dot"></span><div><div class="title">${esc(n.text)}</div><div class="meta">${new Date(n.created).toLocaleString('en-GB')}</div></div></div>`).join('')||'<div class="empty">Brain pleasantly empty. For now.</div>';$('researchItems').innerHTML=state.research.length?state.research.map(researchHtml).join(''):'<div class="empty">No research jobs queued.</div>';if(state.lastSync){$('syncStatus').textContent=`Synced · ${new Date(state.lastSync).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}`;$('calendarBadge').textContent='Connected';$('calendarBadge').classList.add('ready')}if(state.lastReminderSync){$('remindersBadge').textContent='Connected';$('remindersBadge').classList.add('ready')}if(state.lastMailSync&&$('mailBadge')){$('mailBadge').textContent='Connected';$('mailBadge').classList.add('ready')}}
function nav(name){qa('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===name));qa('nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));scrollTo({top:0,behavior:'smooth'})}
qa('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));q('[data-action="capture"]').onclick=()=>nav('capture');q('[data-action="brief"]').onclick=async()=>{const tasks=state.tasks.filter(t=>!t.done).map(t=>`- ${t.text}${t.due?` (due ${t.due})`:''}${t.source?` [${t.source}]`:''}`).join('\n')||'- None';const ev=state.events.filter(e=>(e.date||String(e.start||'').slice(0,10))===todayISO()).map(e=>`- ${e.title} ${e.allDay?'all day':fmtTime(e.start)}`).join('\n')||'- None';const triage=state.triage.sort((a,b)=>(b.score||0)-(a.score||0)).map(t=>`- ${t.title} [${t.source||'PAT'}${t.score?`, score ${t.score}`:''}]`).concat(state.whatsapp.map(w=>`- Unread WhatsApp from ${w.name}`)).join('\n')||'- None';const p=`You are PAT, my practical personal assistant. Triage my day using this context.\n\nCALENDAR\n${ev}\n\nTASKS & REMINDERS\n${tasks}\n\nPOSSIBLE ACTIONS / UNREADS\n${triage}\n\nDecide what is genuinely worth doing today, flag clashes or time pressure, identify anything you can actively research/draft/compare for me, and keep it concise. If something can be done by you now, start doing it.`;await navigator.clipboard.writeText(p);toast('Daily briefing copied');setTimeout(()=>location.href='https://chatgpt.com/',350)};
$('addTask').onclick=()=>{addTask($('taskText').value,$('dueDate').value,$('priority').value);$('taskText').value=''};
$('saveBrain').onclick=()=>{const t=$('brainText').value.trim();if(!t)return;state.brain.unshift({id:crypto.randomUUID(),text:t,created:Date.now()});$('brainText').value='';save();toast('Saved')};
$('brainToTask').onclick=()=>{const t=$('brainText').value.trim();if(!t)return;addTask(t,todayISO(),2,{source:'Capture'});$('brainText').value='';nav('tasks')};
$('brainToReminder').onclick=()=>{const t=$('brainText').value.trim();if(!t)return;addTask(t,todayISO(),2,{source:'PAT reminder',reminderDraft:true});$('brainText').value='';toast('Reminder queued');nav('tasks')};
$('brainToResearch').onclick=()=>{const t=$('brainText').value.trim();if(!t)return;state.research.unshift({id:crypto.randomUUID(),text:t,created:Date.now(),source:'Capture'});$('brainText').value='';save();toast('Moved to research');nav('research')};
$('addResearch').onclick=()=>{const t=$('researchText').value.trim();if(!t)return;state.research.unshift({id:crypto.randomUUID(),text:t,created:Date.now()});$('researchText').value='';save()};
if($('addWhatsApp'))$('addWhatsApp').onclick=()=>{const name=$('whatsappName').value.trim();if(!name)return;const existing=state.whatsapp.find(w=>w.name.toLowerCase()===name.toLowerCase());if(!existing)state.whatsapp.unshift({id:crypto.randomUUID(),name,created:Date.now()});$('whatsappName').value='';save();toast('Unread WhatsApp added')};
qa('.filter').forEach(b=>b.onclick=()=>{qa('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()});
$('exportData').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='PAT-backup.json';a.click();URL.revokeObjectURL(a.href)};
function importPayload(data){if(!data||typeof data!=='object')return;if(Array.isArray(data.events))state.events=data.events;if(Array.isArray(data.reminders)){data.reminders.forEach(r=>{const existing=state.tasks.find(t=>t.externalId&&t.externalId===r.id);if(existing){existing.text=r.title||existing.text;existing.due=r.due||existing.due;existing.done=!!r.done;existing.source=r.source||existing.source||'Apple Reminders'}else state.tasks.push({id:crypto.randomUUID(),externalId:r.id,text:r.title,due:r.due||'',priority:r.priority||2,done:!!r.done,source:r.source||'Apple Reminders',created:Date.now()})});state.lastReminderSync=Date.now()}if(Array.isArray(data.triage))state.triage=data.triage;if(Array.isArray(data.whatsapp))state.whatsapp=data.whatsapp.map(w=>({id:w.id||crypto.randomUUID(),name:w.name||w.sender||'Unknown',created:w.created||Date.now()}));if(Array.isArray(data.mail)){const incoming=data.mail.map(m=>({id:m.id||crypto.randomUUID(),externalId:m.id||null,title:m.subject||'(No subject)',source:'iCloud Mail',sender:m.sender||'',note:m.preview||'',date:m.date||'',score:scoreMail(m),unread:m.unread!==false}));const keep=state.triage.filter(t=>t.source!=='iCloud Mail');state.triage=incoming.filter(m=>m.score>=0).sort((a,b)=>b.score-a.score).concat(keep);state.lastMailSync=Date.now()}state.lastSync=Date.now();save();toast('PAT synced')}
window.PAT_import=importPayload;
const params=new URLSearchParams(location.search);if(params.get('data')){try{importPayload(JSON.parse(decodeURIComponent(params.get('data'))));history.replaceState({},'',location.pathname)}catch(e){console.warn(e)}}
$('importDemo').onclick=()=>importPayload({events:[{id:'demo-1',title:'Example calendar appointment',start:new Date(Date.now()+3600000).toISOString(),date:todayISO(),calendar:'Calendar'}],reminders:[{id:'rem-demo-1',title:'Example Apple reminder',due:todayISO(),source:'Apple Reminders'}],whatsapp:[{name:'Jay'}],mail:[{subject:'Action required: confirm booking',sender:'Example sender',preview:'Please confirm by Friday',unread:true},{subject:'Weekend sale',sender:'Shop',preview:'20% off everything',unread:true}]});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');render();