const KEY='pat-v2';
const legacy=JSON.parse(localStorage.getItem('pat-v1')||'{"tasks":[],"brain":[]}');
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{tasks:legacy.tasks||[],brain:legacy.brain||[],events:[],triage:[],research:[],whatsapp:[],lastSync:null,lastReminderSync:null,lastMailSync:null};
state.tasks=state.tasks||[];state.brain=state.brain||[];state.events=state.events||[];state.triage=state.triage||[];state.research=state.research||[];state.whatsapp=state.whatsapp||[];
const $=id=>document.getElementById(id),q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const todayISO=()=>new Date().toLocaleDateString('en-CA');
const esc=s=>(s||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const save=()=>{localStorage.setItem(KEY,JSON.stringify(state));render()};
function toast(t){const e=$('toast');if(!e)return;e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function fmtDate(d){if(!d)return'';return new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short'}).format(new Date(d+'T12:00:00'))}
function fmtTime(v){if(!v)return'';const d=new Date(v);return isNaN(d)?v:new Intl.DateTimeFormat('en-GB',{hour:'2-digit',minute:'2-digit'}).format(d)}
function plural(n,one,many=one+'s'){return n===1?one:many}
$('todayDate').textContent=new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'long'}).format(new Date());
$('greeting').textContent=(new Date().getHours()<12?'Good morning':new Date().getHours()<18?'Good afternoon':'Good evening')+'.';
$('dueDate').value=todayISO();
function addTask(text,due='',priority=2,extra={}){text=(text||'').trim();if(!text)return;state.tasks.unshift({id:crypto.randomUUID(),text,due,priority:Number(priority),done:false,created:Date.now(),...extra});save()}
window.toggleTask=id=>{const t=state.tasks.find(x=>x.id===id);if(t){t.done=!t.done;save()}};
window.deleteTask=id=>{state.tasks=state.tasks.filter(x=>x.id!==id);save()};
window.deleteResearch=id=>{state.research=state.research.filter(x=>x.id!==id);save()};
window.dismissWhatsApp=id=>{state.whatsapp=state.whatsapp.filter(x=>x.id!==id);save()};
window.dismissTriage=id=>{state.triage=state.triage.filter(x=>x.id!==id);save();toast('Dismissed')};
window.triageToTask=id=>{const t=state.triage.find(x=>x.id===id);if(!t)return;state.tasks.unshift({id:crypto.randomUUID(),text:t.title,due:todayISO(),priority:t.score>=5?1:2,done:false,created:Date.now(),source:t.source||'Triage',note:t.note||''});state.triage=state.triage.filter(x=>x.id!==id);save();toast('Added to tasks')};
window.triageToResearch=id=>{const t=state.triage.find(x=>x.id===id);if(!t)return;state.research.unshift({id:crypto.randomUUID(),text:`${t.title}${t.note?` — ${t.note}`:''}`,created:Date.now(),source:t.source||'Triage'});state.triage=state.triage.filter(x=>x.id!==id);save();toast('Moved to research')};
function taskHtml(t){const overdue=t.due&&t.due<todayISO()&&!t.done;const meta=[t.source||'',t.due?`${overdue?'Overdue · ':''}${fmtDate(t.due)}`:'',t.priority===1?'High priority':''].filter(Boolean).join(' · ');return `<div class="item ${t.done?'done':''}"><input class="check" type="checkbox" ${t.done?'checked':''} onchange="toggleTask('${t.id}')"><div><div class="title">${esc(t.text)}</div>${meta?`<div class="meta">${esc(meta)}</div>`:''}</div><button class="iconBtn" onclick="deleteTask('${t.id}')">×</button></div>`}
function researchHtml(r){return `<div class="researchCard"><div class="item" style="padding:0;border:0"><span class="dot research"></span><div><div class="title">${esc(r.text)}</div><div class="meta">Queued ${new Date(r.created).toLocaleDateString('en-GB')}</div></div><button class="iconBtn" onclick="deleteResearch('${r.id}')">×</button></div><div class="actions"><button class="primary" onclick="researchWithGPT('${r.id}')">Research with ChatGPT</button></div></div>`}
window.researchWithGPT=async id=>{const r=state.research.find(x=>x.id===id);if(!r)return;const p=`Act as my personal assistant. Research this task for me now: ${r.text}. Use current web information where relevant. Give me a concise shortlist, prices/links where applicable, and a clear recommendation. Do the research rather than giving me instructions.`;await navigator.clipboard.writeText(p);toast('Prompt copied — opening ChatGPT');setTimeout(()=>location.href='https://chatgpt.com/',350)};
const HIGH=['action required','urgent','payment','payment failed','overdue','renew','renewal','expires','expiry','appointment','booking','confirm','confirmation needed','delivery problem','failed delivery','account','security','password','verify','verification','reply required','respond','request','deadline','due','school','nursery','invoice','bill','refund','cancellation','cancelled','claim','insurance','mot','tax'];
const MED=['please','reminder','update','change','important','order','delivery','collection','reservation','registration','form','statement','subscription','plan','quote','estimate','review'];
const LOW=['newsletter','sale','offer','discount','promo','promotion','marketing','weekly digest','recommendations','new arrivals'];
function scoreMail(m){const text=`${m.subject||''} ${m.preview||''} ${m.sender||''}`.toLowerCase();let score=m.unread===false?0:1;HIGH.forEach(k=>{if(text.includes(k))score+=3});MED.forEach(k=>{if(text.includes(k))score+=1});LOW.forEach(k=>{if(text.includes(k))score-=2});if(m.flagged)score+=2;return score}
function dayState(){const open=state.tasks.filter(t=>!t.done);const due=open.filter(t=>t.due&&t.due<=todayISO());const overdue=due.filter(t=>t.due<todayISO());const todayEvents=state.events.filter(e=>(e.date||String(e.start||'').slice(0,10))===todayISO()).sort((a,b)=>String(a.start||'').localeCompare(String(b.start||'')));const now=Date.now();const future=todayEvents.filter(e=>e.allDay||!e.start||new Date(e.start).getTime()>=now);const next=future[0]||todayEvents[0]||null;const high=open.filter(t=>t.priority===1).sort((a,b)=>String(a.due||'9999').localeCompare(String(b.due||'9999')));const sortedMail=[...state.triage].sort((a,b)=>(b.score||0)-(a.score||0));const strongMail=sortedMail.filter(t=>(t.score||0)>=4);const pick=overdue[0]||high.find(t=>!t.due||t.due<=todayISO())||due[0]||high[0]||open.find(t=>!t.due)||open[0]||null;return{open,due,overdue,todayEvents,next,high,sortedMail,strongMail,pick}}
function buildSummary(s){const parts=[];if(s.todayEvents.length){const first=s.next||s.todayEvents[0];parts.push(`You’ve got ${s.todayEvents.length} ${plural(s.todayEvents.length,'thing')} in the diary${first?`, with ${first.title}${first.allDay?' all day':first.start?` at ${fmtTime(first.start)}`:''}`:''}.`)}else parts.push('Your diary is clear today.');if(s.due.length){parts.push(`${s.due.length} ${plural(s.due.length,'task')} ${s.due.length===1?'needs':'need'} attention${s.overdue.length?`, including ${s.overdue.length} overdue`:''}.`)}else if(s.open.length){parts.push(`You’ve got ${s.open.length} open ${plural(s.open.length,'task')}, but nothing is due today.`)}else parts.push('You’ve got no open tasks nagging at you.');if(state.whatsapp.length)parts.push(`${state.whatsapp.map(w=>w.name).slice(0,2).join(' and ')} ${state.whatsapp.length===1?'has':'have'} an unread WhatsApp.`);if(s.strongMail.length)parts.push(`I’d look at ${s.strongMail.length} ${plural(s.strongMail.length,'email')} today.`);return parts.join(' ')}
function attentionChips(s){const chips=[];s.overdue.slice(0,2).forEach(t=>chips.push(`<span class="chip task"><span class="dot"></span>${esc(t.text)} · overdue</span>`));state.whatsapp.slice(0,3).forEach(w=>chips.push(`<span class="chip wa"><span class="dot"></span>${esc(w.name)} · WhatsApp</span>`));s.strongMail.slice(0,3).forEach(m=>chips.push(`<span class="chip mail"><span class="dot"></span>${esc(m.title)}</span>`));if(!chips.length&&s.next)chips.push(`<span class="chip event"><span class="dot"></span>${esc(s.next.title)}${s.next.start?` · ${fmtTime(s.next.start)}`:''}</span>`);return chips.join('')||'<span class="chip"><span class="dot"></span>Nothing pressing</span>'}
function render(){const s=dayState();$('dailySummary').textContent=buildSummary(s);$('nextEvent').textContent=s.next?`${s.next.title}${s.next.allDay?' · all day':s.next.start?` · ${fmtTime(s.next.start)}`:''}`:'Nothing fixed in the diary';$('workload').textContent=s.overdue.length?`${s.overdue.length} overdue · ${s.due.length} due`:(s.due.length?`${s.due.length} due today`:(s.open.length?`${s.open.length} open · none due`:'Nothing urgent'));$('patPick').textContent=s.pick?s.pick.text:'Nothing needs your immediate attention.';$('patPickWhy').textContent=s.pick?(s.pick.due&&s.pick.due<todayISO()?'It’s overdue, so I’d clear this first.':s.pick.priority===1?'You marked this high priority, so it gets first refusal on your attention.':s.pick.due===todayISO()?'It’s due today.':'This is the best candidate to move forward today.'):'Enjoy this suspiciously organised moment.';$('attentionChips').innerHTML=attentionChips(s);$('canSortText').textContent=state.research.length?`${state.research.length} ${plural(state.research.length,'job')} waiting — ${state.research[0].text}`:(s.strongMail.length?'I can help turn that email into a reply, task or bit of research.':'Give me shopping, comparisons, bookings or drafting and I’ll prep it.');$('briefSync').textContent=state.lastSync?`Updated ${new Date(state.lastSync).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}`:'Waiting for first sync';const f=q('.filter.active')?.dataset.filter||'open';let tasks=[...state.tasks];if(f==='open')tasks=tasks.filter(t=>!t.done);if(f==='today')tasks=tasks.filter(t=>!t.done&&(!t.due||t.due<=todayISO()));tasks.sort((a,b)=>Number(a.done)-Number(b.done)||a.priority-b.priority||String(a.due).localeCompare(String(b.due)));$('allTasks').innerHTML=tasks.length?tasks.map(taskHtml).join(''):'<div class="empty">No tasks in this view.</div>';$('brainItems').innerHTML=state.brain.slice(0,8).map(n=>`<div class="item"><span class="dot"></span><div><div class="title">${esc(n.text)}</div><div class="meta">${new Date(n.created).toLocaleString('en-GB')}</div></div></div>`).join('')||'<div class="empty">Nothing parked here.</div>';$('researchItems').innerHTML=state.research.length?state.research.map(researchHtml).join(''):'<div class="empty">No research jobs queued.</div>';if(state.lastSync){$('syncStatus').textContent=`Synced · ${new Date(state.lastSync).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}`;$('calendarBadge').textContent='Connected';$('calendarBadge').classList.add('ready')}if(state.lastReminderSync){$('remindersBadge').textContent='Connected';$('remindersBadge').classList.add('ready')}if(state.lastMailSync){$('mailBadge').textContent='Connected';$('mailBadge').classList.add('ready')}}
function nav(name){qa('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===name));qa('nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));scrollTo({top:0,behavior:'smooth'})}
qa('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));q('[data-action="capture"]').onclick=()=>nav('capture');q('[data-action="brief"]').onclick=async()=>{const tasks=state.tasks.filter(t=>!t.done).map(t=>`- ${t.text}${t.due?` (due ${t.due})`:''}${t.source?` [${t.source}]`:''}`).join('\n')||'- None';const ev=dayState().todayEvents.map(e=>`- ${e.title} ${e.allDay?'all day':fmtTime(e.start)}`).join('\n')||'- None';const triage=state.triage.sort((a,b)=>(b.score||0)-(a.score||0)).map(t=>`- ${t.title} [${t.source||'PAT'}${t.score?`, score ${t.score}`:''}]`).concat(state.whatsapp.map(w=>`- Unread WhatsApp from ${w.name}`)).join('\n')||'- None';const research=state.research.map(r=>`- ${r.text}`).join('\n')||'- None';const p=`You are PAT, my practical personal assistant. Give me a concise personal briefing, not a list dump. Tell me what my day looks like, what genuinely matters, what can wait, and what you can actively sort for me now.\n\nCALENDAR\n${ev}\n\nTASKS & REMINDERS\n${tasks}\n\nPOSSIBLE ACTIONS / UNREADS\n${triage}\n\nRESEARCH QUEUE\n${research}\n\nIf you can actively research, compare, draft or plan something now, start doing it.`;await navigator.clipboard.writeText(p);toast('Briefing copied — opening ChatGPT');setTimeout(()=>location.href='https://chatgpt.com/',350)};
$('addTask').onclick=()=>{addTask($('taskText').value,$('dueDate').value,$('priority').value);$('taskText').value=''};
$('saveBrain').onclick=()=>{const t=$('brainText').value.trim();if(!t)return;state.brain.unshift({id:crypto.randomUUID(),text:t,created:Date.now()});$('brainText').value='';save();toast('Saved')};
$('brainToTask').onclick=()=>{const t=$('brainText').value.trim();if(!t)return;addTask(t,todayISO(),2,{source:'Capture'});$('brainText').value='';nav('tasks')};
$('brainToReminder').onclick=()=>{const t=$('brainText').value.trim();if(!t)return;addTask(t,todayISO(),2,{source:'PAT reminder',reminderDraft:true});$('brainText').value='';toast('Reminder queued');nav('tasks')};
$('brainToResearch').onclick=()=>{const t=$('brainText').value.trim();if(!t)return;state.research.unshift({id:crypto.randomUUID(),text:t,created:Date.now(),source:'Capture'});$('brainText').value='';save();toast('Moved to research');nav('research')};
$('addResearch').onclick=()=>{const t=$('researchText').value.trim();if(!t)return;state.research.unshift({id:crypto.randomUUID(),text:t,created:Date.now()});$('researchText').value='';save()};
$('addWhatsApp').onclick=()=>{const name=$('whatsappName').value.trim();if(!name)return;if(!state.whatsapp.some(w=>w.name.toLowerCase()===name.toLowerCase()))state.whatsapp.unshift({id:crypto.randomUUID(),name,created:Date.now()});$('whatsappName').value='';save();toast('Unread WhatsApp added')};
qa('.filter').forEach(b=>b.onclick=()=>{qa('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()});
$('exportData').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='PAT-backup.json';a.click();URL.revokeObjectURL(a.href)};
function importPayload(data){if(!data||typeof data!=='object')return;if(Array.isArray(data.events))state.events=data.events;if(Array.isArray(data.reminders)){data.reminders.forEach(r=>{const existing=state.tasks.find(t=>t.externalId&&t.externalId===r.id);if(existing){existing.text=r.title||existing.text;existing.due=r.due||existing.due;existing.done=!!r.done;existing.source=r.source||existing.source||'Apple Reminders'}else state.tasks.push({id:crypto.randomUUID(),externalId:r.id,text:r.title,due:r.due||'',priority:r.priority||2,done:!!r.done,source:r.source||'Apple Reminders',created:Date.now()})});state.lastReminderSync=Date.now()}if(Array.isArray(data.triage))state.triage=data.triage;if(Array.isArray(data.whatsapp))state.whatsapp=data.whatsapp.map(w=>({id:w.id||crypto.randomUUID(),name:w.name||w.sender||'Unknown',created:w.created||Date.now()}));if(Array.isArray(data.mail)){const incoming=data.mail.map(m=>({id:m.id||crypto.randomUUID(),externalId:m.id||null,title:m.subject||'(No subject)',source:'iCloud Mail',sender:m.sender||'',note:m.preview||'',date:m.date||'',score:scoreMail(m),unread:m.unread!==false}));const keep=state.triage.filter(t=>t.source!=='iCloud Mail');state.triage=incoming.filter(m=>m.score>=0).sort((a,b)=>b.score-a.score).concat(keep);state.lastMailSync=Date.now()}state.lastSync=Date.now();save();toast('PAT synced')}
window.PAT_import=importPayload;
const params=new URLSearchParams(location.search);if(params.get('data')){try{importPayload(JSON.parse(decodeURIComponent(params.get('data'))));history.replaceState({},'',location.pathname)}catch(e){console.warn(e)}}
$('importDemo').onclick=()=>{const now=new Date(),later=new Date(now.getTime()+75*60000);importPayload({events:[{id:'demo-1',title:'Dentist',start:later.toISOString(),date:todayISO(),calendar:'Personal'}],reminders:[{id:'rem-demo-1',title:'Order suitcases',due:todayISO(),source:'Apple Reminders',priority:1},{id:'rem-demo-2',title:'Book MOT',due:todayISO(),source:'Apple Reminders'}],whatsapp:[{name:'Jay'}],mail:[{id:'mail-demo-1',subject:'Action required: confirm booking',sender:'Booking team',preview:'Please confirm by Friday',unread:true}]});state.research=[{id:crypto.randomUUID(),text:'Compare medium suitcases under £120',created:Date.now(),source:'Demo'}];save()};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');render();